/*
============================================================
PROJECT: Business Performance Analysis
LAYER: Gold (Fact + Dimensions)
GOAL: Understand revenue, customers, products, and growth
============================================================

This script answers:
- How healthy is the business?
- What drives revenue?
- Who are the best customers?
- How products perform over time?
- How to segment customers & products for strategy?

============================================================
*/
-- Exploring the database
SELECT * FROM INFORMATION_SCHEMA.TABLES

SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers'

-- Exploring the dimensions 
SELECT DISTINCT country FROM gold.dim_customers

SELECT DISTINCT category , subcategory , product_name FROM gold.dim_products
ORDER BY 1,2,3

-- Date Exploration  -- Finding the first and last order date
SELECT 
	MIN(order_date) AS first_order_date,
	MAX(order_date) AS last_order_date,
	DATEDIFF(month ,MIN(order_date) , MAX(order_date)) AS order_range_months
FROM gold.fact_sales

-- Finding the total sales
SELECT SUM(sales_amount) AS total_sales FROM gold.fact_sales


-- Finding how many items are sold 
SELECT SUM(quantity) AS total_quantity FROM gold.fact_sales


-- The average selling price 
SELECT AVG(price) AS avg_selling_price FROM gold.fact_sales



-- the total number of orders
SELECT COUNT(order_number) AS total_orders,
	   COUNT(DISTINCT order_number) AS distinct_total_orders FROM gold.fact_sales

-- the dataset have repeated order number 

-- total number of products
SELECT COUNT(product_name) AS total_product FROM gold.dim_products 


-- total number of customers
SELECT COUNT(customer_id) AS total_customers FROM gold.dim_customers


-- total number of customers that has placed an order
SELECT COUNT(DISTINCT customer_key) AS total_customer_placed_order FROM gold.fact_sales
	


-- Generating a Report that shows all the key metrics of the business 

SELECT 'total_sales' AS measure_name , SUM(sales_amount) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'total_quantity' , SUM(quantity)  FROM gold.fact_sales
UNION ALL
SELECT 'avg_selling_price' , AVG(price)  FROM gold.fact_sales
UNION ALL
SELECT 'distinct_total_orders' , COUNT(DISTINCT order_number)   FROM gold.fact_sales
UNION ALL
SELECT 'total_product' , COUNT(product_name)   FROM gold.dim_products 
UNION ALL
SELECT 'total_customers', COUNT(customer_id)   FROM gold.dim_customers
UNION ALL
SELECT 'total_customer_placed_order' , COUNT(DISTINCT customer_key)   FROM gold.fact_sales

-- Checking the magnitude 
-- Total customers by country 
SELECT 
	country , 
	COUNT(customer_id) AS total_customers  
FROM gold.dim_customers GROUP BY country 

-- total customers by gender
SELECT 
	gender , 
	COUNT(customer_id) AS total_customers  
FROM gold.dim_customers GROUP BY gender

-- total product by category
SELECT 
	category ,
	COUNT(product_name) AS total_products 
FROM gold.dim_products GROUP BY category

-- average cost in each category
SELECT 
	category , 
	AVG(cost) AS avg_cost  
FROM gold.dim_products GROUP BY category


-- total revenue generated for each category
SELECT 
	p.category ,
	SUM(s.sales_amount) AS total_revenue   
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p 
	ON s.product_key = p.product_key 
GROUP BY p.category
ORDER BY total_revenue DESC

-- total revenue generated by each customer
SELECT 
	c.customer_key ,
	c.first_name ,
	c.last_name ,
	SUM(s.sales_amount) AS total_revenue   
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
	ON s.customer_key = c.customer_key 
GROUP BY 
c.customer_key , 
c.first_name ,
c.last_name
ORDER BY total_revenue DESC

-- distribution of sold items accross country 
SELECT 
	c.country ,
	SUM(quantity) AS total_items_sold   
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
	ON s.customer_key = c.customer_key 
GROUP BY c.country
ORDER BY total_items_sold DESC 

-- Top 5 products by revenue 
-- For more complex queries we can use the windows function for Scalability and flexibility
SELECT TOP 5
	p.product_name ,
	SUM(s.sales_amount) AS total_revenue   
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p 
	ON s.product_key = p.product_key 
GROUP BY p.product_name
ORDER BY total_revenue DESC

-- Bottom 5 products by revenue 
SELECT TOP 5
	p.product_name ,
	SUM(s.sales_amount) AS total_revenue   
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p 
	ON s.product_key = p.product_key 
GROUP BY p.product_name
ORDER BY total_revenue 


-- Top 10 customers with highest revenue 
SELECT 
	c.customer_key ,
	c.first_name ,
	c.last_name ,
	SUM(s.sales_amount) AS total_revenue   
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
	ON s.customer_key = c.customer_key 
GROUP BY 
c.customer_key , 
c.first_name ,
c.last_name
ORDER BY total_revenue DESC

-- Top 3 customers with lowest orders
SELECT TOP 3
	c.customer_key ,
	c.first_name ,
	c.last_name ,
	COUNT(DISTINCT order_number) AS lowest_orders  
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
	ON s.customer_key = c.customer_key 
GROUP BY 
c.customer_key , 
c.first_name ,
c.last_name
ORDER BY lowest_orders  

--Sales over year and Month 
SELECT 
	YEAR(order_date),
	SUM(sales_amount) AS total_sales
FROM gold.fact_sales
WHERE order_date IS NOT NULL
GROUP BY YEAR(order_date)
ORDER BY YEAR(order_date)

SELECT 
	DATETRUNC(month ,order_date) AS order_date,
	SUM(sales_amount) AS total_sales,
	AVG(sales_amount) AS avg_sales,
	SUM(quantity) AS total_quantity,
	COUNT(DISTINCT(customer_key)) AS total_customers
FROM gold.fact_sales
WHERE order_date IS NOT NULL
GROUP BY DATETRUNC(month ,order_date)
ORDER BY DATETRUNC(month ,order_date)

-- Running total sales and avg price over month 
SELECT 
	order_date,
	total_sales,
	SUM(total_sales) OVER (	ORDER BY order_date
							ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS running_total_sales,
	AVG(avg_price) OVER (ORDER BY order_date
							ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS moving_avg_price
FROM
(
SELECT 
	DATETRUNC(month ,order_date) AS order_date,
	SUM(sales_amount) AS total_sales,
	AVG(price) AS avg_price
FROM gold.fact_sales
WHERE order_date IS NOT NULL
GROUP BY DATETRUNC(month ,order_date)
)t

-- Running total sales and avg_price over year
SELECT 
	order_date,
	total_sales,
	SUM(total_sales) OVER (ORDER BY order_date
							ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS running_total_sales ,
	AVG(avg_price) OVER (ORDER BY order_date
							ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS moving_avg_price
FROM
(
SELECT 
	DATETRUNC(year ,order_date) AS order_date,
	SUM(sales_amount) AS total_sales,
	AVG(price) AS avg_price
FROM gold.fact_sales
WHERE order_date IS NOT NULL
GROUP BY DATETRUNC(year ,order_date)
)t

/* Analyze the yearly Performance of products by comparing their
sales to both the average sales performance of the product and the 
previous year's sales */
WITH yearly_sales AS (
SELECT 
	YEAR(s.order_date) AS order_year,
	p.product_name,
	SUM(s.sales_amount) AS current_sales
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
ON s.product_key = p.product_key
WHERE s.order_date IS NOT NULL
GROUP BY 
YEAR(s.order_date) , 
p.product_name
)
SELECT 
		order_year,
		product_name,
		current_sales,
		AVG(current_sales) OVER (PARTITION BY product_name) AS avg_sales,
		current_sales - AVG(current_sales) OVER (PARTITION BY product_name) AS diff_avg,
		CASE WHEN current_sales - AVG(current_sales) OVER (PARTITION BY product_name) > 0 THEN 'Above avg'
		     WHEN current_sales - AVG(current_sales) OVER (PARTITION BY product_name) < 0 THEN 'below avg'
			 ELSE 'Avg'
		 END AS avg_change,
		 LAG(current_sales) OVER (PARTITION BY product_name ORDER BY order_year) AS py_sales,
		 current_sales - LAG(current_sales) OVER (PARTITION BY product_name ORDER BY order_year) AS dif_py_sales,
		 CASE WHEN current_sales - LAG(current_sales) OVER (PARTITION BY product_name ORDER BY order_year ) > 0 THEN 'Increasing'
		      WHEN current_sales - LAG(current_sales) OVER (PARTITION BY product_name ORDER BY order_year ) < 0 THEN 'Decreasing'
		      ELSE  'No Change'
		 END AS previous_yr_change

FROM yearly_sales
ORDER BY product_name , order_year

-- Category that contributes most to the overall sales
WITH category_sales AS (
SELECT 
	category,
	SUM(sales_amount) AS total_sales
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
ON  s.product_key = p.product_key
GROUP BY category )

SELECT 
	category,
	total_sales,
	SUM(total_sales) OVER () AS overall_sales , 
	CONCAT(ROUND((CAST (total_sales AS FLOAT) / SUM(total_sales) OVER())* 100,2),'%') AS percentage_of_sales
FROM category_sales
ORDER BY total_sales DESC

/* Segmenting products into cost and 
count how many products fall into each category */
WITH price_segment AS (
SELECT 
	product_key,
	product_name,
	cost,
	CASE WHEN cost > 1000 THEN 'Above 1000'
		 WHEN cost BETWEEN 100 AND 500 THEN '100 - 500'
		 WHEN cost BETWEEN 500 AND 1000 THEN '500 - 1000'
		 ELSE 'Below 100'
	END AS cost_segment
FROM gold.dim_products
)
SELECT 
	cost_segment,
	COUNT(product_key) AS total_products
FROM price_segment
GROUP BY cost_segment
ORDER BY total_products DESC

/* Group customers into three segments based on their spending behavior:
  - VIP : customers wiht at least 12 months of history and spending more than $5000.
  - Regular : Customer with at least 12 months of history but spending $5000 or less.
  _ New : Customer with a lifespan less than 12 months 
And find the total number of customers by each group */

WITH date_segment AS( 
SELECT 
	customer_key,
	MIN(order_date) AS first_order,
	MAX(order_date) AS last_order,
	DATEDIFF(month,MIN(order_date) , MAX(order_date)) AS life_span,
	SUM(sales_amount) AS total_sales
FROM gold.fact_sales
GROUP BY customer_key
)
SELECT 
	customer_segment,
	COUNT(customer_key) AS total_customers
FROM(
SELECT 
	customer_key,
	life_span,
	CASE WHEN life_span >= 12 AND total_sales > 5000 THEN 'VIP'
		 WHEN life_span >= 12 AND total_sales <= 5000 THEN 'Regular'
		 WHEN life_span < 12 AND total_sales < 5000 THEN 'Normal'
		 ELSE 'New'
	END AS customer_segment
FROM date_segment
)t
GROUP BY customer_segment
ORDER BY total_customers DESC







